{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "62e01878-dcff-4384-b831-1b04e231523c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import glob\n",
    "import matplotlib.pyplot as plt\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import scipy as scp\n",
    "from joblib import Parallel, delayed\n",
    "import multiprocessing\n",
    "import time\n",
    "\n",
    "import torch\n",
    "import pathlib\n",
    "from torch.nn import Parameter\n",
    "\n",
    "import pyro\n",
    "import pyro.contrib.gp as gp\n",
    "import pyro.distributions as dist\n",
    "import pyro.ops.stats as stats\n",
    "from pyro.nn import PyroSample\n",
    "from torch.nn import Parameter\n",
    "\n",
    "smoke_test = ('CI' in os.environ)  # ignore; used to check code integrity in the Pyro repo\n",
    "assert pyro.__version__.startswith('1.9.1')\n",
    "pyro.set_rng_seed(123)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "0e7836ab-179c-4b69-9f7b-27e537525ee1",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>X1</th>\n",
       "      <th>X2</th>\n",
       "      <th>X3</th>\n",
       "      <th>X4</th>\n",
       "      <th>X5</th>\n",
       "      <th>X1.1</th>\n",
       "      <th>X2.1</th>\n",
       "      <th>X3.1</th>\n",
       "      <th>X4.1</th>\n",
       "      <th>X5.1</th>\n",
       "      <th>x_true</th>\n",
       "      <th>x_obs</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>5.944201</td>\n",
       "      <td>-4.562539</td>\n",
       "      <td>-13.838667</td>\n",
       "      <td>-8.940334</td>\n",
       "      <td>1.754179</td>\n",
       "      <td>5.629024</td>\n",
       "      <td>-1.543273</td>\n",
       "      <td>1.277845</td>\n",
       "      <td>-3.747862</td>\n",
       "      <td>-1.416062</td>\n",
       "      <td>2.655087</td>\n",
       "      <td>3.062690</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>-0.001700</td>\n",
       "      <td>-3.527756</td>\n",
       "      <td>-13.411670</td>\n",
       "      <td>-9.283512</td>\n",
       "      <td>0.751805</td>\n",
       "      <td>1.171875</td>\n",
       "      <td>-2.488715</td>\n",
       "      <td>4.120311</td>\n",
       "      <td>-3.107989</td>\n",
       "      <td>-4.763247</td>\n",
       "      <td>3.721239</td>\n",
       "      <td>3.690403</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2.140562</td>\n",
       "      <td>0.921089</td>\n",
       "      <td>-11.273272</td>\n",
       "      <td>1.214724</td>\n",
       "      <td>0.591334</td>\n",
       "      <td>0.520529</td>\n",
       "      <td>2.637156</td>\n",
       "      <td>0.347244</td>\n",
       "      <td>3.822888</td>\n",
       "      <td>-1.290941</td>\n",
       "      <td>5.728534</td>\n",
       "      <td>5.844835</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2.474867</td>\n",
       "      <td>-0.572172</td>\n",
       "      <td>-12.504299</td>\n",
       "      <td>-8.244886</td>\n",
       "      <td>-2.781027</td>\n",
       "      <td>3.288317</td>\n",
       "      <td>-0.472877</td>\n",
       "      <td>1.378758</td>\n",
       "      <td>-3.064271</td>\n",
       "      <td>-6.334764</td>\n",
       "      <td>9.082078</td>\n",
       "      <td>9.065936</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>4.930829</td>\n",
       "      <td>-4.035485</td>\n",
       "      <td>-12.655651</td>\n",
       "      <td>-8.936786</td>\n",
       "      <td>4.688495</td>\n",
       "      <td>6.900609</td>\n",
       "      <td>-1.714549</td>\n",
       "      <td>1.382814</td>\n",
       "      <td>-2.220151</td>\n",
       "      <td>0.802711</td>\n",
       "      <td>2.016819</td>\n",
       "      <td>1.603701</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         X1        X2         X3        X4        X5      X1.1      X2.1  \\\n",
       "1  5.944201 -4.562539 -13.838667 -8.940334  1.754179  5.629024 -1.543273   \n",
       "2 -0.001700 -3.527756 -13.411670 -9.283512  0.751805  1.171875 -2.488715   \n",
       "3  2.140562  0.921089 -11.273272  1.214724  0.591334  0.520529  2.637156   \n",
       "4  2.474867 -0.572172 -12.504299 -8.244886 -2.781027  3.288317 -0.472877   \n",
       "5  4.930829 -4.035485 -12.655651 -8.936786  4.688495  6.900609 -1.714549   \n",
       "\n",
       "       X3.1      X4.1      X5.1    x_true     x_obs  \n",
       "1  1.277845 -3.747862 -1.416062  2.655087  3.062690  \n",
       "2  4.120311 -3.107989 -4.763247  3.721239  3.690403  \n",
       "3  0.347244  3.822888 -1.290941  5.728534  5.844835  \n",
       "4  1.378758 -3.064271 -6.334764  9.082078  9.065936  \n",
       "5  1.382814 -2.220151  0.802711  2.016819  1.603701  "
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# First create the simulation data from the hsgp_simstudy.R script\n",
    "# Then export the data using the exportSimdata_R2P_cluster.R script\n",
    "\n",
    "# Ensure simdata structure is correct and properly reset\n",
    "simdata = []\n",
    "\n",
    "# Read all simdata.csv from path for each N and dim\n",
    "N = [20, 50, 200]\n",
    "dims = [5, 10, 20]\n",
    "for n in N:\n",
    "    simdata_dim = []  # Reset for each sample size\n",
    "    for dim in dims:\n",
    "        simdatapath = glob.glob(f'Simdata{n}N/Simdata{dim}D/*.csv')\n",
    "        simdatapath = sorted(simdatapath)\n",
    "        data = [pd.read_csv(file, index_col=0) for file in simdatapath]\n",
    "        simdata_dim.append(data)  # Store as list of DataFrames\n",
    "    simdata.append(simdata_dim)\n",
    "\n",
    "simdata[0][0][0].head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "53dc5e38-38f1-4496-934f-90693b836238",
   "metadata": {},
   "outputs": [],
   "source": [
    "## Model fit function\n",
    "def gplvmfit(output, input_prior):\n",
    "    pyro.clear_param_store()\n",
    "    # Convert input data to tensors\n",
    "    data = torch.tensor(output.values, dtype=torch.get_default_dtype())\n",
    "    y = data.t()  # Transpose to shape [num_data_points, num_features]\n",
    "    \n",
    "    time = torch.tensor(input_prior.values.squeeze(), dtype=torch.get_default_dtype())\n",
    "    \n",
    "    # Dynamically update the size of X_prior_mean based on output and input_prior lengths\n",
    "    X_prior_mean = torch.zeros(y.size(1), 1, dtype=torch.get_default_dtype()) \n",
    "    X_prior_mean[:, 0] = time[:y.size(1)]  # Ensure that X_prior_mean matches the size of y\n",
    "    \n",
    "    # Define kernel\n",
    "    kernel = gp.kernels.RBF(input_dim=1)\n",
    "    #kernel = gp.kernels.Matern32(input_dim=1)\n",
    "    #kernel = gp.kernels.Matern52(input_dim=1)\n",
    "    \n",
    "    # Use Parameter so PyTorch can track it for optimization\n",
    "    X = Parameter(X_prior_mean.clone(), requires_grad=True)\n",
    "    \n",
    "    # Sampling inducing points using random resampling\n",
    "    Xu = X_prior_mean[torch.randperm(X_prior_mean.size(0))[:10]]\n",
    "    \n",
    "    # Create the Sparse GP model (lower jitter will probably cause positive-definiteness error)\n",
    "    gplvm = gp.models.SparseGPRegression(X, y, kernel, Xu, jitter=1e-3)\n",
    "    \n",
    "    # Pyro sample for X with a normal prior\n",
    "    gplvm.X = pyro.nn.PyroSample(dist.Normal(X_prior_mean, 0.3).to_event())\n",
    "    ## Setting custom priors raise warnings\n",
    "    #gplvm.kernel.lengthscale = PyroSample(dist.HalfNormal(1, 0.05))\n",
    "    #gplvm.kernel.variance = PyroSample(dist.HalfNormal(3, 0.25))\n",
    "    #gplvm.noise = PyroSample(dist.HalfNormal(1, 0.25))\n",
    "    \n",
    "    # Automatic guide for variational inference\n",
    "    gplvm.autoguide(\"X\", dist.Normal)\n",
    "    \n",
    "    # Train the model\n",
    "    losses = gp.util.train(gplvm, num_steps=4000)\n",
    "    \n",
    "    return gplvm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "0d3f87fb-df13-4908-9c26-63d01efb6de6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Sim trial function\n",
    "def simtrial(i, n, j, dim):\n",
    "    cols = [f'X{k}' for k in range(1, dim + 1)]\n",
    "\n",
    "    # Extract the relevant data from simdata\n",
    "    X = simdata[n][j][i].loc[:, cols]\n",
    "    y = simdata[n][j][i][['x_obs']]\n",
    "\n",
    "    # Debugging: print the shapes of X and y to ensure they match where expected\n",
    "    print(f\"Shape of X (features): {X.shape}\")\n",
    "    print(f\"Shape of y (observations): {y.shape}\")\n",
    "\n",
    "    # Ensure that the number of rows (observations) match\n",
    "    if X.shape[0] != y.shape[0]:\n",
    "        raise ValueError(f\"Mismatch in number of rows: X has {X.shape[0]} rows, y has {y.shape[0]} rows\")\n",
    "    fitmodel = gplvmfit(X, y)\n",
    "    #fitmodel.autoguide(\"X\", dist.Normal)    \n",
    "    return fitmodel"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "8156f0d1-877d-455b-9bfc-9b6f7c616262",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processing for 20 sample size...\n",
      "Processing for 5 dimensions...\n",
      "Finished processing for 5D. Number of fits: 50\n",
      "Processing for 10 dimensions...\n",
      "Finished processing for 10D. Number of fits: 50\n",
      "Processing for 20 dimensions...\n",
      "Finished processing for 20D. Number of fits: 50\n",
      "Finished processing for 20N. Number of dimension sets: 3\n",
      "Processing for 50 sample size...\n",
      "Processing for 5 dimensions...\n",
      "Finished processing for 5D. Number of fits: 50\n",
      "Processing for 10 dimensions...\n",
      "Finished processing for 10D. Number of fits: 50\n",
      "Processing for 20 dimensions...\n",
      "Finished processing for 20D. Number of fits: 50\n",
      "Finished processing for 50N. Number of dimension sets: 3\n",
      "Processing for 200 sample size...\n",
      "Processing for 5 dimensions...\n",
      "Finished processing for 5D. Number of fits: 50\n",
      "Processing for 10 dimensions...\n",
      "Finished processing for 10D. Number of fits: 50\n",
      "Processing for 20 dimensions...\n",
      "Finished processing for 20D. Number of fits: 50\n",
      "Finished processing for 200N. Number of dimension sets: 3\n",
      "Total number of sample size sets: 3\n"
     ]
    }
   ],
   "source": [
    "# Fit models in parallel\n",
    "n_sim = 50\n",
    "num_cores = 50\n",
    "\n",
    "# Main list to store fitted models\n",
    "fittedmodels = []\n",
    "\n",
    "# Loop through each sample size (N values)\n",
    "for n, obs in enumerate(N):\n",
    "    print(f\"Processing for {obs} sample size...\")\n",
    "    fittedmodels_dim = []  # Reset for each sample size\n",
    "    \n",
    "    # Loop through each dimension for the given sample size\n",
    "    for j, dim in enumerate(dims):\n",
    "        print(f\"Processing for {dim} dimensions...\")\n",
    "\n",
    "        # Perform parallel simulation trials\n",
    "        fit = Parallel(n_jobs=num_cores)(delayed(simtrial)(i, n, j, dim) for i in range(n_sim))\n",
    "        # Append the fits for this dimension\n",
    "        fittedmodels_dim.append(fit)\n",
    "        \n",
    "        # Verify the number of fits\n",
    "        print(f\"Finished processing for {dim}D. Number of fits: {len(fit)}\")\n",
    "    \n",
    "    # Append the data for all dimensions for the current sample size\n",
    "    fittedmodels.append(fittedmodels_dim)\n",
    "    print(f\"Finished processing for {obs}N. Number of dimension sets: {len(fittedmodels_dim)}\")\n",
    "\n",
    "# Final check: print total counts\n",
    "print(f\"Total number of sample size sets: {len(fittedmodels)}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "1301a1ce-877f-4378-807f-3f3d6e834905",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['fittedmodels_se_widerho.sav']"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "## To save fitted models\n",
    "import joblib\n",
    "filename = 'fittedmodels_se.sav'\n",
    "joblib.dump(fittedmodels, filename)\n",
    "#loadmodels = joblib.load('fittedmodels_se.sav')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "a229f764-1752-4007-a162-2c42dcfede94",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Arrange summary outputs\n",
    "X_mean, X_sd, Rho, Alpha, Sigma, X_true = [], [], [], [], [], []\n",
    "\n",
    "for n in range(len(N)):\n",
    "    X_mean_n, X_sd_n, Rho_n, Alpha_n, Sigma_n, X_true_n = [], [], [], [], [], []\n",
    "    \n",
    "    for j in range(len(dims)):\n",
    "        X_mean_j, X_sd_j, Rho_j, Alpha_j, Sigma_j, X_true_j = [], [], [], [], [], []\n",
    "        \n",
    "        for i in range(n_sim):\n",
    "            # Ensure mode setting is correct\n",
    "            fittedmodels[n][n][i].mode = \"guide\"\n",
    "        \n",
    "            # Extract and convert the required attributes\n",
    "            X_mean_temp = fittedmodels[n][j][i].X_loc.detach().cpu().numpy()  # Ensure data is on CPU\n",
    "            X_sd_temp = fittedmodels[n][j][i].X_scale.detach().cpu().numpy()\n",
    "            Rho_temp = fittedmodels[n][j][i].kernel.lengthscale.detach().cpu().numpy()\n",
    "            Alpha_temp = fittedmodels[n][j][i].kernel.variance.detach().cpu().numpy()\n",
    "            Sigma_temp = fittedmodels[n][j][i].noise.detach().cpu().numpy()\n",
    "            X_true_temp = np.array(simdata[n][j][i][['x_true']].values.squeeze())\n",
    "        \n",
    "            # Append temporary values to lists for current n\n",
    "            X_mean_j.append(X_mean_temp)\n",
    "            X_sd_j.append(X_sd_temp)\n",
    "            Rho_j.append(Rho_temp)\n",
    "            Alpha_j.append(Alpha_temp)\n",
    "            Sigma_j.append(Sigma_temp)\n",
    "            X_true_j.append(X_true_temp)\n",
    "    \n",
    "        # Append the lists for the current n\n",
    "        X_mean_n.append(X_mean_j)\n",
    "        X_sd_n.append(X_sd_j)\n",
    "        Rho_n.append(Rho_j)\n",
    "        Alpha_n.append(Alpha_j)\n",
    "        Sigma_n.append(Sigma_j)\n",
    "        X_true_n.append(X_true_j)\n",
    "    # Append the lists for the current n\n",
    "    X_mean.append(X_mean_n)\n",
    "    X_sd.append(X_sd_n)\n",
    "    Rho.append(Rho_n)\n",
    "    Alpha.append(Alpha_n)\n",
    "    Sigma.append(Sigma_n)\n",
    "    X_true.append(X_true_n)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "0732d5ec-2622-4f44-b79d-eff141d896fb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "    N  Dims  Sim  Obs    X_true      X_mean          X_sd\n",
      "0  20     5    1    1  2.655087  [2.745248]  [0.21365313]\n",
      "1  20     5    1    2  3.721239   [3.49311]  [0.18679981]\n",
      "2  20     5    1    3  5.728534  [5.581703]  [0.18775514]\n",
      "3  20     5    1    4  9.082078   [8.90679]   [0.2167754]\n",
      "4  20     5    1    5  2.016819   [1.76074]  [0.28500476]\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (20, 5)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 10)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (20, 20)\n",
      "Shape of y (observations): (20, 1)\n",
      "Shape of X (features): (50, 5)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 10)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (50, 20)\n",
      "Shape of y (observations): (50, 1)\n",
      "Shape of X (features): (200, 5)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 10)\n",
      "Shape of y (observations): (200, 1)\n",
      "Shape of X (features): (200, 20)\n",
      "Shape of y (observations): (200, 1)\n"
     ]
    }
   ],
   "source": [
    "# Define correct N values for reference\n",
    "N_values = [20, 50, 200]  # Sample sizes\n",
    "Dims_values = [5, 10, 20]   # Output dimensions\n",
    "Sim = 50  # Number of trials\n",
    "\n",
    "# Initialize lists to hold flattened data\n",
    "X_mean_flat, X_sd_flat, X_true_flat = [], [], []\n",
    "N_labels, D_labels, Sim_labels, Obs_labels = [], [], [], []\n",
    "\n",
    "# Flatten the nested lists while keeping track of i, j, k indices\n",
    "for n_idx, (N, mean_n, sd_n, true_n) in enumerate(zip(N_values, X_mean, X_sd, X_true)):  \n",
    "    for j_idx, (D, mean_dim, sd_dim, true_dim) in enumerate(zip(Dims_values, mean_n, sd_n, true_n)):\n",
    "        for sim_idx in range(Sim):  # 50 simulations per (N, D)\n",
    "\n",
    "            # Check available observations (should match N)\n",
    "            num_obs = len(mean_dim[sim_idx])  \n",
    "            if num_obs != N:\n",
    "                print(f\"⚠️ Warning: N={N}, Sim={sim_idx}, Expected Obs={N}, Found Obs={num_obs}\")\n",
    "\n",
    "            for obs_idx in range(min(N, num_obs)):  # Ensure Obs goes from 1 to N\n",
    "                X_mean_flat.append(mean_dim[sim_idx][obs_idx])\n",
    "                X_sd_flat.append(sd_dim[sim_idx][obs_idx])\n",
    "                X_true_flat.append(true_dim[sim_idx][obs_idx])\n",
    "\n",
    "                # Append correct labels\n",
    "                N_labels.append(N)  # Correct Sample Size\n",
    "                D_labels.append(D)  # Output Dimensions\n",
    "                Sim_labels.append(sim_idx + 1)  # Simulation number\n",
    "                Obs_labels.append(obs_idx + 1)  # 1-based Obs index\n",
    "\n",
    "# Create DataFrame with correct labels\n",
    "df = pd.DataFrame({\n",
    "    'N': N_labels,\n",
    "    'Dims': D_labels,\n",
    "    'Sim': Sim_labels,\n",
    "    'Obs': Obs_labels,  # Ensures Obs matches 1 → N correctly\n",
    "    'X_true': X_true_flat,\n",
    "    'X_mean': X_mean_flat,\n",
    "    'X_sd': X_sd_flat\n",
    "})\n",
    "# View the DataFrame\n",
    "print(df.head())  # Printing the first few rows of the DataFrame\n",
    "# Save to CSV\n",
    "df.to_csv('latentXvalues.csv', index=False)\n",
    "# Read the CSV file and clean up any brackets [] in the data\n",
    "df_cleaned = pd.read_csv(\"latentXvalues.csv\").apply(lambda x: x.replace(r\"[\\[\\]]\", \"\", regex=True))\n",
    "\n",
    "# Save the cleaned DataFrame to a new CSV file\n",
    "df_cleaned.to_csv(\"GPLVMpyOut_se.csv\", index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9780b12d-87a0-4b17-891b-678151b1ab71",
   "metadata": {},
   "outputs": [],
   "source": [
    "######################################################## END ######################################################"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
